server:
  port: 9090
  servlet:
    context-path: /admin-server/v1

spring:
  application:
    name: admin-server
  thymeleaf:
    check-template-location: false
  security:
    user:
      name: admin
      password: admin